http://localhost:3001

###

POST http://localhost:5001
Content-Type: application/json
# Accept: application/json

{
  "test": "test text",
  "time": {{$timestamp}},
  "more": {{$guid}}
}

###

http://localhost:4000/posts
