version: '2'
services:
  proxy:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "3333:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
      # use this if you want to servce static files.
      # - assets:/app/public/assets
  db:
    image: postgres
    # ports:
    #   - "5432:5432"
    # still developments stuff.
    environment:
      - POSTGRES_PASSWORD=pin-mouse-password
      - POSTGRES_USER=pin-mouse
      - POSTGRES_DB=pin-mouse
  app:
    # build: pin-mouse
    image: pin-app:latest
    depends_on:
      # consider adding the wait-for-it script. https://github.com/vishnubob/wait-for-it
      - db
    volumes:
      # to serve static files.
      - assets:/app/public/assets
    environment:
      - RAILS_ENV=production
      # still not the real secret. :)
      - SECRET_KEY_BASE=onetwothreefourfive
      - RAILS_LOG_TO_STDOUT=true
      - PIN_MOUSE_DATABASE_USERNAME=pin-mouse
      - PIN_MOUSE_DATABASE_PASSWORD=pin-mouse-password
      - RAILS_SERVE_STATIC_FILES=true
    command: ["/usr/bin/env", "bash", "-c", "rails assets:precompile && rails db:migrate && rails server -b 0.0.0.0"]
    # ports:
    #   - "3000:3000"
volumes:
  assets:

# TODO: need to extract most env variables to external config that wont go to github.