source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem "webmock", "~> 3.3"
  gem "faker", "~> 1.8"
end

# gem 'pinterest-api', '~> 0.4.0'
gem 'rack-cors'
gem 'httparty'
gem 'bootstrap'
gem 'jquery-rails'
gem 'font-awesome-sass'
gem 'whenever', require: false

# added this gem to help with env variables
gem 'dotenv-rails', groups: [:development, :test]