export const ADD_TODO = 'ADD_TODO';

export const FETCH_ITEMS_IS_LOADING = 'FETCH_ITEMS_IS_LOADING';
export const FETCH_ITEMS_HAS_ERROR = 'FETCH_ITEMS_HAS_ERROR';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const FETCH_REPOS_IS_LOADING = 'FETCH_REPOS_IS_LOADING';
export const FETCH_REPOS_HAS_ERROR = 'FETCH_REPOS_HAS_ERROR';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
